from enum import Enum, auto

class TweakID(Enum):
    # tweaks page
    PosterBoard = auto()
    Templates = auto()
    StatusBar = auto()
    IconThemes = auto()

    # springboard
    LockScreenFootnote = auto()
    WatchOSCompatibility = auto()
    AirDropDisableTimeLimit = auto()
    SBDontLockAfterCrash = auto()
    SBDontDimOrLockOnAC = auto()
    SBHideLowPowerAlerts = auto()
    SBHideACPower = auto()
    SBNeverBreadcrumb = auto()
    SBShowSupervisionTextOnLockScreen = auto()
    AirplaySupport = auto()
    SBMinimumLockscreenIdleTime = auto()
    SBAlwaysShowSystemApertureInSnapshots = auto()
    HideDICompletely = auto()
    SBShowAuthenticationEngineeringUI = auto()
    UseFloatingTabBar = auto()
    SBDisableIconParallax = auto()
    SBHideSearchAffordance = auto()

    # mobilegestalt (ported from leminlimez/Nugget; not supported on iOS 26.2+)
    DynamicIsland = auto()
    SupportsDynamicIsland = auto()
    ModelName = auto()
    BootChime = auto()
    EnableLGLPM = auto()
    DisableLGLPM = auto()
    RdarFix = auto()
    ChargeLimit = auto()
    CollisionSOS = auto()
    TapToWake = auto()
    CameraButton = auto()
    Parallax = auto()
    StageManager = auto()
    iPadOS = auto()
    iPadOSCacheData = auto()
    iPadApps = auto()
    Shutter = auto()
    Pencil = auto()
    ActionButton = auto()
    InternalStorage = auto()
    InternalInstall = auto()
    SRD = auto()
    AOD = auto()
    AODVibrancy = auto()
    # NOTE: in leminlimez/Nugget this tweak lives in load_eligibility()
    # (eligibility page); the tweak definition itself is verbatim.
    AIGestalt = auto()

    # eligibility (ported verbatim from leminlimez/Nugget's load_eligibility();
    # removed by GoldenNugget, re-added here using Nugget's original code)
    EUEnabler = auto()
    AIEligibility = auto()
    AIFeatureFlags = auto()
    AIFeatureFlagsUI = auto()
    SpoofModel = auto()
    SpoofHardware = auto()
    SpoofCPU = auto()
    CreateBRFolders = auto()

    # feature flags (ported from leminlimez/Nugget; removed by GoldenNugget,
    # re-added here using Nugget's original flag definitions)
    ClockAnim = auto()
    Lockscreen = auto()
    PhotoUI = auto()
    AI = auto()
    KioskMode = auto()

    # internal
    SBBuildNumber = auto()
    RTL = auto()
    LTR = auto()
    SBIconVisibility = auto()
    # NOTE: MetalForceHudEnabled was removed (audit B28) — upstream Nugget's
    # load_internal() defines it, but this fork carries no spec for it.
    iMessageDiagnosticsEnabled = auto()
    IDSDiagnosticsEnabled = auto()
    VCDiagnosticsEnabled = auto()
    AccessoryDeveloperEnabled = auto()
    KeyFlick = auto()
    DisableThermal = auto()

    DisableSecondsHand = auto()
    DisableSearchingWebsites = auto()
    ShowButtonHints = auto()

    AppStoreDebug = auto()
    NotesDebugMode = auto()
    BKDigitizerVisualizeTouches = auto()
    BKHideAppleLogoOnLaunch = auto()
    EnableWakeGestureHaptic = auto()
    PlaySoundOnPaste = auto()
    AnnounceAllPastes = auto()

    # liquid glass — Round 6 (2026-10-02, per user order): 71 audited candidates
    # added for pre-beta developer release. All unverified on device.
    # See ~/workspace/riset/AUDIT-KANDIDAT-BARU.md for audit details.
    SolariumForceFallback = auto()
    # Deprecated alias for backward compat with old presets (pre-4.0)
    ForceSolariumFallback = SolariumForceFallback
    DisableSolariumSwiftUI = auto()
    GlassLegibility2 = auto()
    SolariumFeatureFlags = auto()
    GranularSpringBoard = auto()
    LGLPMGestalt = auto()
    DisallowGlassTime = auto()
    DisableLockScreenSpecular = auto()
    DisableClockSpecular = auto()
    DisableGlassLockScreen = auto()
    DisableGlassDock = auto()
    FlatIconsEverywhere = auto()
    DisableWidgetSpecular = auto()
    DisableDockSpecular = auto()
    DisableFolderSpecular = auto()
    ExcludeClearGlassShadows = auto()
    ExcludeDockShadow = auto()
    ExcludeSearchShadow = auto()
    DisableOuterRefraction = auto()
    DisableSolariumHDR = auto()
    DisableSpecularMotion = auto()
    DisableCompactChrome = auto()
    DisableSpecularEverywhere = auto()
    SuppressDICompletely = auto()
    DisableGlassDI = auto()
    DisallowGlassDI = auto()
    DisableIslandSpecular = auto()
    DisableGlassEverywhere = auto()
    DisallowGlassEverywhere = auto()
    DisableRefractionEverywhere = auto()
    ExcludeAllGlassShadows = auto()
    FlatDockEverywhere = auto()
    DisableGlassBlur = auto()
    DisallowGlassKeyboard = auto()
    # Blurr Motion (2026-10-03): the single candidate from the DesignLibrary
    # dossier whose key string is attested in the 23G83 binary
    # (~/workspace/riset/wave11/DOSSIER-BLURR-MOTION.md). Normal tweak, no
    # badge: unverified status lives in its description, not a lock.
    BlurrMotion = auto()
    # status bar visual (non-glass)
    StatusBarOverrides = auto()
    ShowSystemServices = auto()
    ShowBatteryPercentage = auto()
    # lock screen custom (non-glass)
    CustomLockDate = auto()
    # notifications (non-glass, Apple keys)
    NotifDisplayStyle = auto()
    NotifPreview = auto()
    NotifScheduled = auto()
    NotifSummarize = auto()
    NotifAnnounce = auto()
    NotifHighlights = auto()
    NotifAlertType = auto()
    NotifGrouping = auto()
    NotifVisibility = auto()
    NotifPriority = auto()
    # home screen non-glass
    DisableParallax = auto()
    HideSearchAffordance = auto()
    IconVisibility = auto()
    DisableClockSeconds = auto()
    # keyboard (non-glass)
    KbAutocorrect = auto()
    KbPrediction = auto()
    KbPredBar = auto()
    KbGestureIntro = auto()
    KbAutoLists = auto()
    # siri classic (non-glass)
    SiriEnabled = auto()
    SiriDataSharing = auto()
    SiriAutoPunct = auto()
    SiriVoiceTrigger = auto()
    SiriTriggerPhrase = auto()
    SiriSpeakerTTS = auto()
    SiriDeclined = auto()
    SiriVocab = auto()
    # animation (non-glass)
    AnimDragCoeff = auto()

    # risky (ported from leminlimez/Nugget's load_risky())
    DisableOTAFile = auto()
    CustomResolution = auto()

    # daemons
    Daemons = auto()
    ClearScreenTimeAgentPlist = auto()

    # Liquid Glass Tweaks (Nugget) — verbatim from leminlimez/Nugget
    # v7.4.1 (src/tweaks/nugget_lg.py). Own IDs so the Nugget set lives
    # next to, never inside, the WorkSlop v4 set above.
    NuggetForceSolariumFallback = auto()
    NuggetDisableSolarium = auto()
    NuggetIgnoreSolariumLinkedOnCheck = auto()
    NuggetNoLiquidClock = auto()
    NuggetNoLiquidDock = auto()
    NuggetDisableSpecularMotion = auto()
    NuggetDisableOuterRefraction = auto()
    NuggetDisableSolariumHDR = auto()
    NuggetSolariumFFSwiftUI = auto()
    NuggetSolariumFFSpringBoard = auto()
    NuggetSolariumFFIconServices = auto()
    NuggetSolariumFFDocumentCamera = auto()
    NuggetSolariumFFPhotos = auto()
    NuggetSolariumFFAppleMediaServices = auto()
    NuggetSolariumFFSharing = auto()
    NuggetSolariumFFMail = auto()

    # Liquid Glass Disable (Beta 1) — new feature (2026-10-04): two
    # delivery routes for the Beta 1 SolariumForceFallback key. Own IDs so
    # the frozen v4 set above (incl. TweakID.SolariumForceFallback, which
    # stages the same key into the managed overlay) is never touched.
    # See src/tweaks/lg_disable.py.
    LGDisableG2 = auto()  # managed overlay (.GlobalPreferences.plist, ManagedPreferencesDomain)
    LGDisableG1 = auto()  # device file merge (HomeDomain .GlobalPreferences.plist, diff-gated)